#!/bin/sh

LANGUAGE=$1
TEXT=$2
SPEED=$3
PITCH=$4

NEPO_TTS_FOLDER=/media/card/NEPO-TTS
TMP_FOLDER="$NEPO_TTS_FOLDER/tmp"
CONVERTED_WAV_FILE="$TMP_FOLDER/output.wav"

ESPEAK_BIN="$NEPO_TTS_FOLDER/speak"
RESAMPLER_BIN="$NEPO_TTS_FOLDER/resampler"

mkdir -p $TMP_FOLDER

LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$NEPO_TTS_FOLDER" $ESPEAK_BIN "$TEXT" -v $LANGUAGE -s $SPEED -p $PITCH --stdout | $RESAMPLER_BIN $CONVERTED_WAV_FILE
